// The provider registry. Each entry records only what the provider
// documents: a rule the provider doesn't document keeps its default (dots
// significant, no subaddress separator, no subdomain addressing), since
// merging two people's addresses under one key is worse than missing a
// duplicate. `src/sources` cites every fact here, with the date it was last
// checked; test/providers.test.ts keeps the two in step.
import type { ProviderInfo } from './types';

// Every domain Fastmail offers for new addresses.
const fastmailDomains: readonly string[] = [
  '123mail.org',
  '150mail.com',
  '150ml.com',
  '16mail.com',
  '2-mail.com',
  '4email.net',
  '50mail.com',
  'airpost.net',
  'aliencamel.com',
  'allmail.net',
  'bestmail.us',
  'cluemail.com',
  'elitemail.org',
  'emailcorner.net',
  'emailengine.net',
  'emailengine.org',
  'emailgroups.net',
  'emailplus.org',
  'emailuser.net',
  'eml.cc',
  'f-m.fm',
  'fast-email.com',
  'fast-mail.org',
  'fastem.com',
  'fastemail.us',
  'fastemailer.com',
  'fastest.cc',
  'fastimap.com',
  'fastmail.ca',
  'fastmail.cn',
  'fastmail.co.uk',
  'fastmail.com',
  'fastmail.com.au',
  'fastmail.de',
  'fastmail.es',
  'fastmail.fm',
  'fastmail.fr',
  'fastmail.im',
  'fastmail.in',
  'fastmail.jp',
  'fastmail.mx',
  'fastmail.net',
  'fastmail.nl',
  'fastmail.org',
  'fastmail.se',
  'fastmail.to',
  'fastmail.tw',
  'fastmail.uk',
  'fastmail.us',
  'fastmailbox.net',
  'fastmessaging.com',
  'fea.st',
  'fmail.co.uk',
  'fmailbox.com',
  'fmgirl.com',
  'fmguy.com',
  'foobox.com',
  'foobox.net',
  'ftml.net',
  'h-mail.us',
  'hailmail.net',
  'imap-mail.com',
  'imap.cc',
  'imapmail.org',
  'immerbox.com',
  'immermail.com',
  'inoutbox.com',
  'internet-e-mail.com',
  'internet-mail.org',
  'internetemails.net',
  'internetmailing.net',
  'jetemail.net',
  'justemail.net',
  'letterboxes.org',
  'lifetimeaddress.com',
  'mail-central.com',
  'mail-page.com',
  'mailas.com',
  'mailbolt.com',
  'mailc.net',
  'mailcan.com',
  'mailforce.net',
  'mailhaven.com',
  'mailingaddress.org',
  'mailite.com',
  'mailmight.com',
  'mailnew.com',
  'mailsent.net',
  'mailservice.ms',
  'mailup.net',
  'mailworks.org',
  'mailzone.com',
  'ml1.net',
  'mm.st',
  'myfastmail.com',
  'mymacmail.com',
  'nospammail.net',
  'onepost.net',
  'ownmail.net',
  'penguinmail.com',
  'permanentmail.com',
  'petml.com',
  'pobox.com',
  'postinbox.com',
  'postpro.net',
  'proinbox.com',
  'promessage.com',
  'realemail.net',
  'reallyfast.biz',
  'reallyfast.info',
  'rushpost.com',
  'sent.as',
  'sent.at',
  'sent.com',
  'siemprebox.com',
  'siempremail.com',
  'speedpost.net',
  'speedymail.org',
  'ssl-mail.com',
  'swift-mail.com',
  'the-fastest.net',
  'the-quickest.com',
  'theinternetemail.com',
  'veribox.net',
  'veryfast.biz',
  'veryspeedy.net',
  'warpmail.net',
  'xsmail.com',
  'yepmail.net',
  'your-mail.com',
];

/**
 * Every provider the registry knows, in no particular order.
 *
 * @example
 * ```ts
 * import { providers } from '@email-utils/classifier/providers';
 *
 * providers.find((provider) => provider.id === 'gmail');
 * // => { name: 'Gmail', kind: 'personal', dotsSignificant: false }
 * ```
 */
export const providers: readonly ProviderInfo[] = [
  {
    id: 'gmail',
    name: 'Gmail',
    kind: 'personal',
    domains: ['gmail.com', 'googlemail.com'],
    canonicalDomain: 'gmail.com',
    mxPatterns: ['gmail-smtp-in.l.google.com', '*.gmail-smtp-in.l.google.com'],
    dotsSignificant: false,
    hyphensSignificant: true,
    subaddressSeparator: '+',
    subdomainAddressing: false,
  },
  {
    id: 'google-workspace',
    name: 'Google Workspace',
    kind: 'business',
    domains: [],
    mxPatterns: [
      'smtp.google.com',
      'aspmx.l.google.com',
      '*.aspmx.l.google.com',
      'aspmx2.googlemail.com',
      'aspmx3.googlemail.com',
      'aspmx4.googlemail.com',
      'aspmx5.googlemail.com',
    ],
    dotsSignificant: true,
    hyphensSignificant: true,
    subaddressSeparator: '+',
    subdomainAddressing: false,
  },
  {
    id: 'outlook',
    name: 'Outlook.com',
    kind: 'personal',
    domains: [
      'outlook.com',
      'hotmail.com',
      'live.com',
      'msn.com',
      'passport.com',
      'windowslive.com',
      'hotmail.ca',
      'hotmail.co.jp',
      'hotmail.co.uk',
      'hotmail.com.au',
      'hotmail.com.br',
      'hotmail.de',
      'hotmail.es',
      'hotmail.fr',
      'hotmail.it',
      'live.ca',
      'live.co.uk',
      'live.com.au',
      'live.de',
      'live.fr',
      'live.it',
      'live.nl',
      'outlook.com.br',
      'outlook.de',
      'outlook.es',
      'outlook.fr',
      'outlook.it',
      'outlook.jp',
    ],
    mxPatterns: ['*.olc.protection.outlook.com'],
    dotsSignificant: true,
    hyphensSignificant: true,
    subaddressSeparator: '+',
    subdomainAddressing: false,
  },
  {
    id: 'microsoft365',
    name: 'Microsoft 365',
    kind: 'business',
    domains: [],
    mxPatterns: [
      '*.mail.protection.outlook.com',
      '*.mx.microsoft',
      '*.mail.eo.outlook.com',
      '*.mail.protection.outlook.de',
    ],
    dotsSignificant: true,
    hyphensSignificant: true,
    subaddressSeparator: '+',
    subdomainAddressing: false,
  },
  {
    id: 'yahoo',
    name: 'Yahoo Mail',
    kind: 'personal',
    domains: [
      'yahoo.com',
      'myyahoo.com',
      'ymail.com',
      'rocketmail.com',
      'yahoo.ca',
      'yahoo.co.uk',
      'yahoo.com.au',
      'yahoo.com.br',
      'yahoo.de',
      'yahoo.es',
      'yahoo.fr',
      'yahoo.in',
      'yahoo.it',
    ],
    mxPatterns: [
      'mta5.am0.yahoodns.net',
      'mta6.am0.yahoodns.net',
      'mta7.am0.yahoodns.net',
      'mx-eu.mail.am0.yahoodns.net',
      'mx-apac.mail.gm0.yahoodns.net',
    ],
    dotsSignificant: true,
    hyphensSignificant: true,
    subdomainAddressing: false,
  },
  {
    id: 'aol',
    name: 'AOL Mail',
    kind: 'personal',
    domains: ['aol.com', 'aim.com', 'aol.co.uk', 'aol.de', 'aol.fr'],
    mxPatterns: ['mx-aol.mail.gm0.yahoodns.net'],
    dotsSignificant: true,
    hyphensSignificant: true,
    subdomainAddressing: false,
  },
  {
    id: 'icloud',
    name: 'iCloud Mail',
    kind: 'personal',
    domains: ['icloud.com', 'me.com', 'mac.com'],
    canonicalDomain: 'icloud.com',
    mxPatterns: ['*.mail.icloud.com'],
    dotsSignificant: true,
    hyphensSignificant: true,
    subdomainAddressing: false,
  },
  {
    id: 'proton',
    name: 'Proton Mail',
    kind: 'personal',
    domains: ['proton.me', 'protonmail.com', 'protonmail.ch', 'pm.me'],
    mxPatterns: ['mail.protonmail.ch', 'mailsec.protonmail.ch'],
    dotsSignificant: true,
    hyphensSignificant: true,
    subaddressSeparator: '+',
    subdomainAddressing: false,
  },
  {
    id: 'fastmail',
    name: 'Fastmail',
    kind: 'personal',
    domains: fastmailDomains,
    mxPatterns: [
      'in1-smtp.messagingengine.com',
      'in2-smtp.messagingengine.com',
    ],
    dotsSignificant: true,
    hyphensSignificant: true,
    subaddressSeparator: '+',
    subdomainAddressing: true,
  },
  {
    id: 'zoho',
    name: 'Zoho Mail',
    kind: 'personal',
    domains: ['zoho.com', 'zohomail.com'],
    mxPatterns: ['smtpin.zoho.com', 'smtpin2.zoho.com', 'smtpin3.zoho.com'],
    dotsSignificant: true,
    hyphensSignificant: true,
    subdomainAddressing: false,
  },
  {
    id: 'zoho-business',
    name: 'Zoho Mail for business',
    kind: 'business',
    domains: [],
    mxPatterns: [
      'mx.zoho.com',
      'mx2.zoho.com',
      'mx3.zoho.com',
      'mx.zoho.eu',
      'mx2.zoho.eu',
      'mx3.zoho.eu',
      'mx.zoho.in',
      'mx2.zoho.in',
      'mx3.zoho.in',
      'mx.zoho.com.au',
      'mx2.zoho.com.au',
      'mx3.zoho.com.au',
      'mx.zoho.jp',
      'mx2.zoho.jp',
      'mx3.zoho.jp',
      'mx.zoho.sa',
      'mx2.zoho.sa',
      'mx3.zoho.sa',
      'mx.zoho.uk',
      'mx2.zoho.uk',
      'mx3.zoho.uk',
      'mx.zohocloud.ca',
      'mx2.zohocloud.ca',
      'mx3.zohocloud.ca',
      'mx.zoho.com.cn',
      'mx2.zoho.com.cn',
    ],
    dotsSignificant: true,
    hyphensSignificant: true,
    subdomainAddressing: false,
  },
  {
    id: 'yandex',
    name: 'Yandex Mail',
    kind: 'personal',
    domains: ['yandex.ru', 'yandex.com', 'yandex.by', 'yandex.kz', 'ya.ru'],
    canonicalDomain: 'yandex.ru',
    mxPatterns: ['mx.yandex.ru'],
    dotsSignificant: true,
    hyphensSignificant: false,
    subaddressSeparator: '+',
    subdomainAddressing: false,
  },
  {
    id: 'yandex-360',
    name: 'Yandex 360 for Business',
    kind: 'business',
    domains: [],
    mxPatterns: ['mx.yandex.net'],
    dotsSignificant: true,
    hyphensSignificant: true,
    subdomainAddressing: false,
  },
  {
    id: 'gmx',
    name: 'GMX',
    kind: 'personal',
    domains: [
      'gmx.net',
      'gmx.de',
      'gmx.at',
      'gmx.ch',
      'gmx.com',
      'gmx.us',
      'gmx.co.uk',
    ],
    mxPatterns: ['*.emig.gmx.net', 'mx00.gmx.net', 'mx01.gmx.net'],
    dotsSignificant: true,
    hyphensSignificant: true,
    subdomainAddressing: false,
  },
  {
    id: 'web-de',
    name: 'WEB.DE',
    kind: 'personal',
    domains: ['web.de'],
    mxPatterns: ['mx-ha02.web.de', 'mx-ha03.web.de'],
    dotsSignificant: true,
    hyphensSignificant: true,
    subdomainAddressing: false,
  },
  {
    id: 'mail-ru',
    name: 'Mail.ru',
    kind: 'personal',
    domains: ['mail.ru', 'inbox.ru', 'list.ru', 'bk.ru', 'internet.ru'],
    mxPatterns: ['mxs.mail.ru'],
    dotsSignificant: true,
    hyphensSignificant: true,
    subdomainAddressing: false,
  },
  {
    id: 'tuta',
    name: 'Tuta Mail',
    kind: 'personal',
    domains: [
      'tuta.com',
      'tutanota.com',
      'tutanota.de',
      'tutamail.com',
      'tuta.io',
      'keemail.me',
    ],
    mxPatterns: ['mail.tutanota.de'],
    dotsSignificant: true,
    hyphensSignificant: true,
    subdomainAddressing: false,
  },
  {
    id: 'hey',
    name: 'HEY',
    kind: 'personal',
    domains: ['hey.com'],
    mxPatterns: ['home-mx.app.hey.com'],
    dotsSignificant: true,
    hyphensSignificant: true,
    subdomainAddressing: false,
  },
  {
    id: 'namecheap',
    name: 'Namecheap Email Forwarding',
    kind: 'registrar',
    domains: [],
    mxPatterns: [
      'eforward1.registrar-servers.com',
      'eforward2.registrar-servers.com',
      'eforward3.registrar-servers.com',
      'eforward4.registrar-servers.com',
      'eforward5.registrar-servers.com',
    ],
    dotsSignificant: true,
    hyphensSignificant: true,
    subdomainAddressing: false,
  },
];
